spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 112123657465-qh8qqqea3aa2128h2aa28mu7b17kfl4l.apps.googleusercontent.com
            client-secret: NLYThpU5L92Ss7N5wgtmaL1a
          facebook:
            client-id: 451698182369606
            client-secret: c94d25c620f6e0c0467cf61d50599a6b
custom:
  oauth2:
    kakao:
      client-id: 5e2e53517595d66a1a0dca92cec5e928
